name: Deploy

on:
  workflow_dispatch:
  push:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Build apps
      uses: hyoo-ru/mam_build@master2
      with:
        token: ${{ secrets.GH_PAT }}
        package: mol/icon
        modules: demo
        
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'mol/icon/demo/-'
